version: '3.4'

services:
  ordersapiapppv012:
    image: ${DOCKER_REGISTRY-}ordersapiapppv012
    build:
      context: .
      dockerfile: OrdersApiAppPV012/Dockerfile
  database:
    image: postgres:latest
    container_name: db_postgres
    environment:
      - POSTGRES_USER=postgres  
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=OrderDb
    ports:
      - 5432:5432